# Generated by Django 2.2.5 on 2019-10-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freightAndInsurance', models.FloatField()),
                ('otherCosts', models.FloatField()),
                ('customsRate', models.FloatField()),
                ('exciseTax', models.FloatField()),
                ('vat', models.FloatField()),
                ('surtax', models.FloatField()),
                ('withholdingTax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CostOfGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=200)),
                ('part_no', models.TextField()),
                ('product_description', models.TextField()),
                ('unitMarketPrice', models.FloatField()),
                ('quantity', models.FloatField()),
                ('markup', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
