# Generated by Django 2.2.5 on 2019-10-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConstantFields',
            new_name='ConstantField',
        ),
        migrations.RenameModel(
            old_name='CostOfGoods',
            new_name='CostOfGood',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
