# Generated by Django 3.0.1 on 2020-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
