# Generated by Django 3.0.1 on 2020-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='organization',
            field=models.CharField(default='no organization set', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='project_type',
            field=models.CharField(default='no project set', max_length=200),
            preserve_default=False,
        ),
    ]
