# Generated by Django 3.0.1 on 2020-02-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_auto_20200210_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='costofgood',
            name='exchange_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
