# Generated by Django 3.0.1 on 2020-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_costofgood_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costofgood',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
