# Generated by Django 3.0.3 on 2020-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='note_choices',
            field=models.CharField(choices=[('vat', 'vat'), ('price_valid', 'price_valid'), ('price_birr', 'price_birr'), ('delivery', 'delivery'), ('payment_term', 'payment_term'), ('installation', 'installation'), ('discrepancy', 'discrepancy')], default='0', max_length=100),
            preserve_default=False,
        ),
    ]
